#!/bin/env bash
# +-- created by: achmur -------------- time4Linux ------------------------+ #
# |     __  __ __  __    _                           __           .--.     | #
# |    / /_/ // / / /   (_)___  __  ___  __   ____  / /          |ö_ö |    | #
# |   / __/ // /_/ /   / / __ \/ / / / |/_/  / __ \/ /           |\ü/ |    | #
# |  / /_/__  __/ /___/ / / / / /_/ />  < _ / /_/ / /           //   \ \   | #
# |  \__/  /_/ /_____/_/_/ /_/\__,_/_/|_/(_) .___/_/           (|     | )  | #
# |                                       /_/                 /'\_   _/`\\ | #
# |  Version     : 1.0                         2023-02-21     \___)=(___// | #
# +------------------------------------------ 2024-10-06 ------------------+ #
# |  Description : ZSH configuration setup                                 | #
# +------------------------------------------------------------------------+ #
#
# |------------------------ zsh FUNCTIONS        --------------------------| #
REPO=$(pwd)
USER_LOK=$1
GIT_LOK=$HOME/t4Linux/github/zsh

fonts() {
  cp -r $REPO/fonts $HOME/$USER_LOK/
  ln -s $HOME/$USER_LOK/fonts/ $HOME/.local/share/fonts
  fc-cache -f -v
}

create() {
  mkdir -p $HOME/$USER_LOK $GIT_LOK
  cp -r $REPO/zsh/ $HOME/$USER_LOK/zsh
  ln -s $HOME/$USER_LOK/zsh/zshenv $HOME/.zshenv
  echo "ZDOTDIR=$HOME/$USER_LOK/zsh" >>$HOME/.zshenv
  location="export MY_FILES"
  location2="export MY_GIT_LOK"
  echo $location"="$HOME/$USER_LOK >>$HOME/.zshenv
  echo $location2"="$GIT_LOK >>$HOME/.zshenv
  if [[ ! -d $HOME/.local/share/fonts ]]; then
    fonts
  else
    rm -fr $HOME/.local/share/fonts
    fonts
  fi
}
# |------------------------ zsh plugin installer --------------------------| #
zsh_plug() {
  git -C $GIT_LOK/ clone https://github.com/$1.git
}

# |---------------------  checking for script args  -----------------------| #
#
if [ ${#} -eq 0 ]; then
  echo -e "Please enter the location of your all DOTFILES folder "
  echo -e "Suggested t4_zsh .t4Linux"
  exit 78
fi
# |---------------------     MAIN SCRIPT            -----------------------| #
#

if ! command -v zsh &>/dev/null; then
  sudo apt install zsh -y
  chsh -s $(which zsh)
else
  chsh -s $(which zsh)
fi

curl -s https://ohmyposh.dev/install.sh | bash -s

# |------------------------ setting dir location --------------------------| #
if [[ ! -d $HOME/$USER_LOK ]]; then
  create
else
  mv $HOME/$USER_LOK/zsh $HOME/$USER_LOK/zsh.bak
  create
fi

# |------------------------ plugins installation -------------------------| #
if [[ ! -d $GIT_LOK/fzf ]]; then
  a=prefix=\'~/.fzf\'
  b=prefix=
  c=$GIT_LOK/fzf
  zsh_plug "junegunn/fzf"
  sed -ie "s@$a@$b$c@g" $GIT_LOK/fzf/install
  $GIT_LOK/fzf/install --all --completion --no-fish --no-bash --xdg --no-update-rc
  ln -s $GIT_LOK/fzf/bin/fzf $HOME/.local/bin/fzf
  ln -s $GIT_LOK/fzf/bin/fzf-preview.sh $HOME/.local/bin/fzf-preview.sh
fi

if [[ ! -d $GIT_LOK/fzf-tab ]]; then
  zsh_plug "Aloxaf/fzf-tab"
fi

if [[ ! -d $GIT_LOK/zsh-autosuggestions ]]; then
  zsh_plug "zsh-users/zsh-autosuggestions"
fi

if [[ ! -d $GIT_LOK/zsh-completions ]]; then
  zsh_plug "zsh-users/zsh-completions"
fi

if [[ ! -d $GIT_LOK/zsh-syntax-highlighting ]]; then
  zsh_plug "zsh-users/zsh-syntax-highlighting"
fi

if [[ ! -d $GIT_LOK/powerlevel10k ]]; then
  zsh_plug "romkatv/powerlevel10k"
fi

if [[ ! -d $GIT_LOK/zsh-history-substring-search ]]; then
  zsh_plug "zsh-users/zsh-history-substring-search"
fi

if [[ ! -d $GIT_LOK/fzf-zsh-completions/ ]]; then
  zsh_plug "chitoku-k/fzf-zsh-completions"
fi

if [[ ! -d $GIT_LOK/zsh-z ]]; then
  zsh_plug "agkozak/zsh-z"
fi

if [[ ! -L $HOME/.config/zsh ]]; then
  ln -s $HOME/$USER_LOK/zsh/ $HOME/.config/zsh
fi
if [[ ! -d $HOME/$USER_LOK/fonts ]]; then
  ln -s $REPO/fonts $HOME/.local/share/fonts
fi
# sed '$d' $HOME/$USER_LOK/zsh/.zshrc
# rm $HOME/.zshrc
