#!/bin/env bash
# +-- created by: achmur -------------- time4Linux ------------------------+ #
# |     __  __ __  __    _                           __           .--.     | #
# |    / /_/ // / / /   (_)___  __  ___  __   ____  / /          |ö_ö |    | #
# |   / __/ // /_/ /   / / __ \/ / / / |/_/  / __ \/ /           |\ü/ |    | #
# |  / /_/__  __/ /___/ / / / / /_/ />  < _ / /_/ / /           //   \ \   | #
# |  \__/  /_/ /_____/_/_/ /_/\__,_/_/|_/(_) .___/_/           (|     | )  | #
# |                                       /_/                 /'\_   _/`\\ | #
# |  Version     : 1.0                         2023-02-21     \___)=(___// | #
# +------------------------------------------ 2023-03-06 ------------------+ #
# |  Description : ZSH configuration setup                                 | # 
# +------------------------------------------------------------------------+ #
#
# |------------------------ zsh FUNCTIONS        --------------------------| #
REPO=$(pwd)
USER_LOK=$1

create(){
  mkdir -p $HOME/$USER_LOK 
  cp -r $REPO/zsh/ $HOME/$USER_LOK/zsh
  ln -s $HOME/$USER_LOK/zsh/zshenv $HOME/.zshenv
  echo "ZDOTDIR=$HOME/$USER_LOK/zsh" >> $HOME/.zshenv
  location="export MY_FILES"
  echo $location"="$HOME/$USER_LOK >> $HOME/.zshenv
}
# |------------------------ zsh plugin installer --------------------------| #
zsh_plug(){
  git -C $HOME/$USER_LOK/zsh/ clone https://github.com/$1.git
}

# |---------------------  checking for script args  -----------------------| #
# 
if [ ${#} -eq 0 ]; then
  echo "Please enter the location of your all DOTFILES folder"
  exit 78
fi
# |---------------------     MAIN SCRIPT            -----------------------| #
# 


if ! command -v zsh &>/dev/null; then
  sudo apt install zsh -y
  chsh -s $(which zsh)
else
  chsh -s $(which zsh)
fi

# |------------------------ setting dir location --------------------------| #
if [[ ! -d $HOME/$USER_LOK ]]; then
  create
else 
  mv $HOME/$USER_LOK/zsh $HOME/$USER_LOK/zsh.bak
  create
fi

# |------------------------ plugins installation -------------------------| #
if [[ ! -d $HOME/$USER_LOK/zsh/fzf ]]; then
  a=prefix=\'~/.fzf\'
  b=prefix=
  c=$HOME/$USER_LOK/fzf
  zsh_plug "junegunn/fzf"
  sed -ie "s@$a@$b$c@g" $HOME/$USER_LOK/zsh/fzf/install 
  $HOME/$USER_LOK/zsh/fzf/install --all --completion --no-fish --no-bash
  mv ~/.fzf.zsh $HOME/$USER_LOK/zsh/settings/fzf.zsh
fi

if [[ ! -d $HOME/$USER_LOK/zsh/fzf-tab ]]; then
  zsh_plug "Aloxaf/fzf-tab"
fi

if [[ ! -d $HOME/$USER_LOK/zsh/zsh-autosuggestions ]]; then
  zsh_plug "zsh-users/zsh-autosuggestions"
fi

if [[ ! -d $HOME/$USER_LOK/zsh/zsh-completions ]]; then
  zsh_plug "zsh-users/zsh-completions"
fi

if [[ ! -d $HOME/$USER_LOK/zsh/zsh-syntax-highlighting ]]; then
  zsh_plug "zsh-users/zsh-syntax-highlighting"
fi

if [[ ! -d $HOME/$USER_LOK/zsh/powerlevel10k ]]; then
  zsh_plug "romkatv/powerlevel10k"
fi

if [[ ! -d $HOME/$USER_LOK/zsh/zsh-history-substring-search ]]; then
  zsh_plug "zsh-users/zsh-history-substring-search"
fi

if [[ ! -d $HOME/$USER_LOK/zsh/fzf-zsh-completions/ ]]; then
  zsh_plug "chitoku-k/fzf-zsh-completions"
fi

if [[ ! -d $HOME/$USER_LOK/zsh/zsh-z ]]; then
  zsh_plug "agkozak/zsh-z"
fi

if [[ ! -L $HOME/.config/zsh ]]; then
  ln -s $HOME/$USER_LOK/zsh/ $HOME/.config/zsh
fi
if [[ ! -d $HOME/$USER_LOK/aliases ]]; then
  cp -r $REPO/aliases $HOME/$USER_LOK
fi
if [[ ! -d $HOME/$USER_LOK/fonts ]]; then
  ln -s $REPO/fonts $HOME/.local/share/fonts
fi
# sed '$d' $HOME/$USER_LOK/zsh/.zshrc
rm $HOME/.zshrc

