git:
  paging:
    colorArg: always
    pager: delta --dark --paging=never
gui:
  showIcons: true
  showFileTree: true # for rendering changes files in a tree format
  showCommandLog: true
os:
  editCommand: 'lvim'
