#!/usr/bin/env bash

# this is a simple config for herbstluftwm

hc() {
	herbstclient "$@"
}

hc emit_hook reload

#########################################
############## autostart ################
#########################################

dunst &
spice-vdagent &
nm-applet &
eval $(/usr/bin/gnome-keyring-daemon --start --components=ssh,gpg,pkcs11,secrets) &
# eval $(gnome-keyring-daemon --start) &
eval "$(ssh-agent -s)" &
ssh-add &
~/.local/bin/monitors.sh &
~/.config/herbstluftwm/polybar/launch.sh &
nitrogen --restore &
picom --config ~/.config/dk/picom.conf &
~/B_A/Nextcloud-3.11.0-x86_64.AppImage &

export GNOME_KEYRING_CONTROL GNOME_KEYRING_PID GPG_AGENT_INFO SSH_AUTH_SOCK
export GTK_THEME="Adwaita:dark" nautilus
export SSH_AUTH_SOCK=$XDG_RUNTIME_DIR/keyring/ssh

########################################
#
# (re)load sxhkd for keybinds
if hash sxhkd >/dev/null 2>&1; then
	pkill sxhkd
	sxhkd -c "$HOME/.config/herbstluftwm/sxhkd/sxhkdrc" &
fi

xsetroot -solid '#5A8E3A'

# keybindings
source $HOME/.config/herbstluftwm/keys

hc keybind $Mod-Shift-q quit
hc keybind $Mod-Shift-r reload

# moving clients in tiling and floating mode
hc keybind $Mod-Shift-Left shift left
hc keybind $Mod-Shift-Down shift down
hc keybind $Mod-Shift-Up shift up
hc keybind $Mod-Shift-Right shift right

# hc keybind $Mod-Shift-h or / shift left / \
# 	chain , lock , shift_to_monitor -l , focus_monitor -l , unlock
# hc keybind $Mod-Shift-j or / shift down / \
# 	chain , lock , shift_to_monitor -d , focus_monitor -d , unlock
# hc keybind $Mod-Shift-k or / shift up / \
# 	chain , lock , shift_to_monitor -u , focus_monitor -u , unlock
# hc keybind $Mod-Shift-l or / shift right / \
# 	chain , lock , shift_to_monitor -r , focus_monitor -r , unlock

# splitting frames
# create an empty frame at the specified direction
hc keybind $Mod-u chain , split bottom 0.5 , focus -e d
hc keybind $Mod-o chain , split right 0.5 , focus -e r
# let the current frame explode into subframes
hc keybind $Mod-Control-space split explode

# resizing frames and floating clients
resizestep=0.02
hc keybind $Mod-Control-h resize left +$resizestep
hc keybind $Mod-Control-j resize down +$resizestep
hc keybind $Mod-Control-k resize up +$resizestep
hc keybind $Mod-Control-l resize right +$resizestep

# tags
source $HOME/.config/herbstluftwm/tag_per_monitor

tag_names=({1..5})
tag_keys=({1..5} 0)
#
# hc rename default "${tag_names[0]}" || true
# for i in "${!tag_names[@]}"; do
# 	hc add "${tag_names[$i]}"
# 	key="${tag_keys[$i]}"
# 	if [ -n "$key" ]; then
# 		hc keybind "$Mod-$key" use_index "$i"
# 		hc keybind "$Mod-Shift-$key" move_index "$i"
# 	fi
# done

# cycle through tags
# hc keybind $Mod-period use_index +1 --skip-visible
# hc keybind $Mod-comma use_index -1 --skip-visible

# layouting
hc keybind $Mod-r remove
hc keybind $Mod-s floating toggle
hc keybind $Mod-f fullscreen toggle
hc keybind $Mod-Shift-f set_attr clients.focus.floating toggle
hc keybind $Mod-Shift-d set_attr clients.focus.decorated toggle
hc keybind $Mod-Shift-m set_attr clients.focus.minimized true
hc keybind $Mod-Control-m jumpto last-minimized
hc keybind $Mod-p pseudotile toggle
# The following cycles through the available layouts within a frame, but skips
# layouts, if the layout change wouldn't affect the actual window positions.
# I.e. if there are two windows within a frame, the grid layout is skipped.
hc keybind $Mod-space \
	or , and . compare tags.focus.curframe_wcount = 2 \
	. cycle_layout +1 vertical horizontal max vertical grid \
	, cycle_layout +1

# mouse
hc mouseunbind --all
hc mousebind $Mod-Button1 move
hc mousebind $Mod-Button2 zoom
hc mousebind $Mod-Button3 resize

# focus
hc keybind $Mod-Tab cycle_monitor
hc keybind $Mod-Shift-Tab cycle_all -1
hc keybind $Mod-c cycle
hc keybind $Mod-i jumpto urgent

# theme
hc attr theme.tiling.reset 1
hc attr theme.floating.reset 1
hc set frame_border_active_color '#222222cc'
hc set frame_border_normal_color '#101010cc'
hc set frame_bg_normal_color '#565656aa'
hc set frame_bg_active_color '#345F0Caa'
hc set frame_border_width 1
hc set show_frame_decorations 'focused_if_multiple'
hc set frame_bg_transparent on
hc set frame_transparent_width 5
hc set frame_gap 4

hc attr theme.title_height 15
hc attr theme.title_when never
hc attr theme.title_font 'Dejavu Sans:pixelsize=12' # example using Xft
# hc attr theme.title_font '-*-fixed-medium-r-*-*-13-*-*-*-*-*-*-*'
hc attr theme.title_depth 3 # space below the title's baseline
hc attr theme.active.color '#345F0Cef'
hc attr theme.title_color '#ffffff'
hc attr theme.normal.color '#323232dd'
hc attr theme.urgent.color '#7811A1dd'
hc attr theme.tab_color '#1F1F1Fdd'
hc attr theme.active.tab_color '#2B4F0Add'
hc attr theme.active.tab_outer_color '#6C8257dd'
hc attr theme.active.tab_title_color '#ababab'
hc attr theme.normal.title_color '#898989'
hc attr theme.inner_width 1
hc attr theme.inner_color black
hc attr theme.border_width 3
hc attr theme.floating.border_width 4
hc attr theme.floating.outer_width 1
hc attr theme.floating.outer_color black
hc attr theme.active.inner_color '#789161'
hc attr theme.urgent.inner_color '#9A65B0'
hc attr theme.normal.inner_color '#606060'
# copy inner color to outer_color
for state in active urgent normal; do
	hc substitute C theme.${state}.inner_color \
		attr theme.${state}.outer_color C
done
hc attr theme.tiling.outer_width 1
hc attr theme.background_color '#141414'

hc set window_gap 8
hc set frame_padding 1
hc set smart_window_surroundings on
hc set smart_frame_surroundings on
hc set default_direction_external_only false

# rules
hc unrule -F
#hc rule class=XTerm tag=3 # move all xterms to tag 3
hc rule focus=on # normally focus new clients
hc rule floatplacement=smart
#hc rule focus=off # normally do not focus new clients
# give focus to most common terminals
#hc rule class~'(.*[Rr]xvt.*|.*[Tt]erm|Konsole)' focus=on
hc rule windowtype~'_NET_WM_WINDOW_TYPE_(DIALOG|UTILITY|SPLASH)' floating=on
hc rule windowtype='_NET_WM_WINDOW_TYPE_DIALOG' focus=on
hc rule windowtype~'_NET_WM_WINDOW_TYPE_(NOTIFICATION|DOCK|DESKTOP)' manage=off
hc rule fixedsize floating=on

hc set tree_style '╾│ ├└╼─┐'

# unlock, just to be sure
hc unlock

# do multi monitor setup here, e.g.:
# hc set_monitors 1280x1024+0+0 1280x1024+1280+0
# or simply:
hc detect_monitors

# find the panel
# panel=~/.config/herbstluftwm/panel.sh
# [ -x "$panel" ] || panel=/etc/xdg/herbstluftwm/panel.sh
# for monitor in $(hc list_monitors | cut -d: -f1); do
# 	# start it on each monitor
# 	"$panel" "$monitor" &
# done
