#!/bin/bash
#
Mod=Mod1 # Use alt as the main modifier
#Mod=Mod4   # Use the super key as the main modifier

# REMOVE ALL EXISTING KEYBINDINGS #
#---------------------------------#
hc keyunbind --ALL

###################################
#           SYSTEM                #
###################################
hc keybind $Mod-space \
	or , and . compare tags.focus.curframe_wcount = 2 \
	. cycle_layout +1 vertical horizontal grid \
	, cycle_layout +1

# herbstluftwm

hc keybind $Mod-Shift-q quit
hc keybind $Mod-Shift-r reload

hc keybind $Mod-r remove
hc keybind $Mod-s floating toggle
hc keybind $Mod-f fullscreen toggle

hc keybind $Mod-Shift-m set_attr clients.focus.minimized true
hc keybind $Mod-Control-m jumpto last-minimized

# moving clients in tiling and floating mode
hc keybind $Mod-Shift-Left shift left
hc keybind $Mod-Shift-Down shift down
hc keybind $Mod-Shift-Up shift up
hc keybind $Mod-Shift-Right shift right

# splitting frames
# create an empty frame at the specified direction
hc keybind $Mod-u chain , split bottom 0.5 , focus -e d
hc keybind $Mod-o chain , split left 0.5 , focus -e r
# let the current frame explode into subframes
hc keybind $Mod-Control-space split explode

# resizing frames and floating clients
resizestep=0.02
hc keybind $Mod-Control-h resize left +$resizestep
hc keybind $Mod-Control-j resize down +$resizestep
hc keybind $Mod-Control-k resize up +$resizestep
hc keybind $Mod-Control-l resize right +$resizestep

# focus
hc keybind $Mod-Tab cycle_monitor
hc keybind $Mod-Shift-Tab cycle_all -1
hc keybind $Mod-c cycle
hc keybind $Mod-i jumpto urgent

#         mause settings          #
#+++++++++++++++++++++++++++++++++#

hc mouseunbind --all
hc set mouse_recenter_gap 1     # mouse on center of monitor
hc set focus_follows_mouse true # focus following mouse
hc mousebind $Mod-Button1 move
hc mousebind $Mod-Button2 zoom
hc mousebind $Mod-Button3 resize

# MONITORS

hc set swap_monitors_to_get_tag false
hc set focus_crosses_monitor_boundaries true

# basic movement in tiling and floating mode
# focusing clients
hc keybind $Mod-Left focus left
hc keybind $Mod-Down focus down
hc keybind $Mod-Up focus up
hc keybind $Mod-Right focus right

hc keybind $Mod-Return spawn scratch scratchpad
hc keybind $Mod-Shift-Return spawn scratchpad3
hc keybind $Mod-Shift-e spawn alacritty -t power.sh -e power.sh

hc keybind $Mod-Shift-p spawn scratch2 Proton

# hc rule index=e
# will prefer to place a new window in an existing, empty frame

# System controls #
#-----------------#
# hc keybind $Mod-Shift-c spawn alacritty -t logout -e herbst-logout.sh
# hc keybind $Mod-Control-r reload
# hc keybind $Mod-Shift-q close
# hc keybind $Mod-Shift-Return spawn "${TERMINAL:-kitty}" #
